---

-   hosts:  skitty
    remote_user:    deploy
    sudo:   True
    sudo_user:  root
    vars_files:
        -   instance_vars/{{env}}.yml
        -   node_vars/main.yml
    roles:
        -   skitty_appserver