---

-   include: git_clone.yml
    when: not vagrant

-   name: NPM | Install skitty packages
    npm: path={{instance.root_dir}}skitty_v2/
    ignore_errors: yes

-   name: PM2 | Check list of Node.js apps running
    command: "pm2 list"
    register: pm2_list
    changed_when: false

-   name: PM2 | Start Skitty app
    command: "chdir={{instance.root_dir}}skitty_v2/ pm2 start server.js --name {{instance.name}}"
    when: "pm2_list.stdout.find('skitty') == -1"

-   name: PM2 | Restart Skity Application
    command: pm2 restart {{instance.name}}
    when: "pm2_list.stdout.find('skitty') == 1"

