---

-   include: git_clone.yml
    when: not vagrant

-   name: NPM | Install skitty packages
    npm: path={{instance.root_dir}}skitty_v2/
    ignore_errors: yes

-   name: Skitty | Check existence of plugdj config file
    stat: path={{instance.root_dir}}{{instance.name}}_v2/config/plugdj.js
    register: plugdj_file

-   name: Skitty | Delete file if it exists
    file: path={{instance.root_dir}}{{instance.name}}_v2/config/plugdj.js   state=absent
    when: "plugdj_file.stat.exists == True"
    sudo: True
    sudo_user: root

-   name: Skitty | Check existence of plugdj config file
    stat: path={{instance.root_dir}}{{instance.name}}_v2/config/plugdj.js
    register: plugdj_file

-   name: Skitty | Re-create plugdj file
    template: src=plugdj.j2 dest={{instance.root_dir}}{{instance.name}}_v2/config/plugdj.js
    when: "plugdj_file.stat.exists == False"
    sudo: True
    sudo_user: root

-   include: pm2.yml
    when: not vagrant

# -   name: PM2 | Deleting all apps
#     command: pm2 -s delete all
#     ignore_errors: yes

# -   name: PM2 | Check list of Node.js apps running
#     command: "pm2 list"
#     register: pm2_list
#     changed_when: false

# -   name: PM2 | Start Skitty app
#     shell: "chdir={{instance.root_dir}}skitty_v2/ pm2 start server.js --name {{instance.name}}"
#     when: "pm2_list.stdout.find('skitty') == -1"

