---

# PM2 Tasks

-   name: PM2 | Installing startup script
    shell: pm2 startup ubuntu >& /dev/null chdir=~/ executable=/bin/bash
    ignore_errors: yes

-   name: PM2 | Deleting all apps
    command: pm2 -s delete all
    ignore_errors: yes

-   name: PM2 | Check list of Node.js apps running
    command: "pm2 list"
    register: pm2_list
    changed_when: false

-   name: Server | Check existence of app file
    stat: path={{instance.root_dir}}{{instance.name}}_v2/server.js
    register: app_file

-   name: PM2 | Start Skitty app
    command: "chdir={{ instance.root_dir }}/skitty_v2/ pm2 start server.js --name {{ instance.name }}"
    when: "pm2_list.stdout.find('skitty') == -1 and app_file.stat.exists == True"

# Restart app to resolve any process error
-   name: PM2 | Restart Skitty app
    command: "pm2 restart {{ instance.name }}"